blueprint:
  name: NAMRON 4 Channel ZigBee Switch v2.3.964
  description: Controls lights based on ZHA events for each endpoint.
  domain: automation
  input:

    device_id:
      name: Device ID
      description: The device ID of the ZHA switch.
      selector:
        text: {}
    light_entity_1:
      name: Light Entity 1
      description: The light entity controlled by endpoint 1.
      selector:
        entity:
          domain: light
    light_entity_2:
      name: Light Entity 2
      description: The light entity controlled by endpoint 2.
      selector:
        entity:
          domain: light
    light_entity_3:
      name: Light Entity 3
      description: The light entity controlled by endpoint 3.
      selector:
        entity:
          domain: light
    light_entity_4:
      name: Light Entity 4
      description: The light entity controlled by endpoint 4.
      selector:
        entity:
          domain: light
    delay_1:
      name: Dim delay entity 1
      description: Sets sleep time in dimming automation for selected endpoint
      default: 500
      selector:
        number:
          min: 0
          max: 1500
          unit_of_measurement: "ms"
          mode: slider
    delay_2:
      name: Dim delay entity 2
      description: Sets sleep time in dimming automation for selected endpoint
      default: 500
      selector:
        number:
          min: 0
          max: 1500
          unit_of_measurement: "ms"
          mode: slider
    delay_3:
      name: Dim delay entity 3
      description: Sets sleep time in dimming automation for selected endpoint
      default: 500
      selector:
        number:
          min: 0
          max: 1500
          unit_of_measurement: "ms"
          mode: slider
    delay_4:
      name: Dim delay entity 4
      description: Sets sleep time in dimming automation for selected endpoint
      default: 500
      selector:
        number:
          min: 0
          max: 1500
          unit_of_measurement: "ms"
          mode: slider

    brightness_step_1:
      name: Brightness Step for Light Entity 1
      initial: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
    brightness_step_2:
      name: Brightness Step for Light Entity 2
      initial: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
    brightness_step_3:
      name: Brightness Step for Light Entity 3
      initial: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider
    brightness_step_4:
      name: Brightness Step for Light Entity 4
      initial: 10
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: "on"
    id: on1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: "off"
    id: off1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: stop_with_on_off
    id: onRelease1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: stop
    id: onReleaseDown1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: "on"
    id: on2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: "off"
    id: off2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: stop_with_on_off
    id: onRelease2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: stop
    id: onReleaseDown2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: "on"
    id: on3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: "off"
    id: off3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: stop_with_on_off
    id: onRelease3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: stop
    id: onReleaseDown3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: "on"
    id: on4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: "off"
    id: off4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: stop_with_on_off
    id: onRelease4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: stop
    id: onReleaseDown4

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on1
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity_1
            data:
              brightness_pct: 100
      - conditions:
          - condition: trigger
            id: off1
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity_1
      - conditions:
          - condition: trigger
            id: onHold1
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: onHold1
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: "{{ states('input_number.brightness_step_1') | int(default=0) }}"
                  target:
                    entity_id: !input light_entity_1
                - delay:
                    milliseconds: !input delay_1
                  enabled: true
      - conditions:
          - condition: trigger
            id: offHold1
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: offHold1
                - condition: numeric_state
                  entity_id: !input light_entity_1
                  attribute: brightness
                  above: 2
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: "{{ (-1 * states('input_number.brightness_step_1') | int(default=0)) }}"
                    entity_id: !input light_entity_1
                - delay:
                    milliseconds: !input delay_1
                  enabled: true
    alias: Entity 1
  - choose:
      - conditions:
          - condition: trigger
            id: on2
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity_2
            data:
              brightness_pct: 100
      - conditions:
          - condition: trigger
            id: off2
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity_2
      - conditions:
          - condition: trigger
            id: onHold2
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: onHold2
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity_2
                  data:
                    brightness_step_pct: 10
                - delay:
                    milliseconds: !input delay_2
      - conditions:
          - condition: trigger
            id: offHold2
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: offHold2
                - condition: numeric_state
                  entity_id: !input light_entity_2
                  attribute: brightness
                  above: 2
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity_2
                  data:
                    brightness_step_pct: -10
                - delay:
                    milliseconds: !input delay_2
    alias: Entity 2
  - choose:
      - conditions:
          - condition: trigger
            id: on3
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity_3
            data:
              brightness_pct: 100
      - conditions:
          - condition: trigger
            id: off3
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity_3
      - conditions:
          - condition: trigger
            id: onHold3
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: onHold3
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity_3
                  data:
                    brightness_step_pct: 10
                - delay:
                    milliseconds: !input delay_3
      - conditions:
          - condition: trigger
            id: offHold3
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: offHold3
                - condition: numeric_state
                  entity_id: !input light_entity_3
                  attribute: brightness
                  above: 2
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity_3
                  data:
                    brightness_step_pct: -10
                - delay:
                    milliseconds: !input delay_3
    alias: Entity 3
  - choose:
      - conditions:
          - condition: trigger
            id: on4
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_entity_4
            data:
              brightness_pct: 100
      - conditions:
          - condition: trigger
            id: off4
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input light_entity_4
      - conditions:
          - condition: trigger
            id: onHold4
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: onHold4
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity_4
                  data:
                    brightness_step_pct: 10
                - delay:
                    milliseconds: !input delay_4
      - conditions:
          - condition: trigger
            id: offHold4
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: offHold4
                - condition: numeric_state
                  entity_id: !input light_entity_4
                  attribute: brightness
                  above: 2
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input light_entity_4
                  data:
                    brightness_step_pct: -10
                - delay:
                    milliseconds: !input delay_4
    alias: Entity 4
mode: restart
