blueprint:
  name: NAMRON 4 Channel ZigBee Switch v2
  description: Controls lights based on ZHA events with customizable actions for each endpoint bbb.
  domain: automation
  input:
    device_id:
      name: Device ID
      description: The device ID of the ZHA switch.
      selector:
        text: {}
    light_entity_1:
      name: Light Entity 1
      description: The light entity controlled by endpoint 1.
      selector:
        entity:
          domain: light
    light_entity_2:
      name: Light Entity 2
      description: The light entity controlled by endpoint 2.
      selector:
        entity:
          domain: light
    light_entity_3:
      name: Light Entity 3
      description: The light entity controlled by endpoint 3.
      selector:
        entity:
          domain: light
    light_entity_4:
      name: Light Entity 4
      description: The light entity controlled by endpoint 4.
      selector:
        entity:
          domain: light

    # Custom Actions for Endpoint 1
    custom_action_1_on:
      name: Custom Action 1 On
      description: Custom action to perform when endpoint 1 is triggered "on".
      default: []
      selector:
        action: {}
    custom_action_1_off:
      name: Custom Action 1 Off
      description: Custom action to perform when endpoint 1 is triggered "off".
      default: []
      selector:
        action: {}
    custom_action_1_on_hold:
      name: Custom Action 1 On Hold
      description: Custom action to perform when endpoint 1 is held.
      default: []
      selector:
        action: {}
    custom_action_1_off_hold:
      name: Custom Action 1 Off Hold
      description: Custom action to perform when endpoint 1 is released from hold.
      default: []
      selector:
        action: {}

    # Custom Actions for Endpoint 2
    custom_action_2_on:
      name: Custom Action 2 On
      description: Custom action to perform when endpoint 2 is triggered "on".
      default: []
      selector:
        action: {}
    custom_action_2_off:
      name: Custom Action 2 Off
      description: Custom action to perform when endpoint 2 is triggered "off".
      default: []
      selector:
        action: {}
    custom_action_2_on_hold:
      name: Custom Action 2 On Hold
      description: Custom action to perform when endpoint 2 is held.
      default: []
      selector:
        action: {}
    custom_action_2_off_hold:
      name: Custom Action 2 Off Hold
      description: Custom action to perform when endpoint 2 is released from hold.
      default: []
      selector:
        action: {}

    # Custom Actions for Endpoint 3
    custom_action_3_on:
      name: Custom Action 3 On
      description: Custom action to perform when endpoint 3 is triggered "on".
      default: []
      selector:
        action: {}
    custom_action_3_off:
      name: Custom Action 3 Off
      description: Custom action to perform when endpoint 3 is triggered "off".
      default: []
      selector:
        action: {}
    custom_action_3_on_hold:
      name: Custom Action 3 On Hold
      description: Custom action to perform when endpoint 3 is held.
      default: []
      selector:
        action: {}
    custom_action_3_off_hold:
      name: Custom Action 3 Off Hold
      description: Custom action to perform when endpoint 3 is released from hold.
      default: []
      selector:
        action: {}

    # Custom Actions for Endpoint 4
    custom_action_4_on:
      name: Custom Action 4 On
      description: Custom action to perform when endpoint 4 is triggered "on".
      default: []
      selector:
        action: {}
    custom_action_4_off:
      name: Custom Action 4 Off
      description: Custom action to perform when endpoint 4 is triggered "off".
      default: []
      selector:
        action: {}
    custom_action_4_on_hold:
      name: Custom Action 4 On Hold
      description: Custom action to perform when endpoint 4 is held.
      default: []
      selector:
        action: {}
    custom_action_4_off_hold:
      name: Custom Action 4 Off Hold
      description: Custom action to perform when endpoint 4 is released from hold.
      default: []
      selector:
        action: {}

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: "on"
    id: on1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: "off"
    id: off1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: stop_with_on_off
    id: onRelease1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: stop
    id: onReleaseDown1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: "on"
    id: on2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: "off"
    id: off2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: stop_with_on_off
    id: onRelease2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: stop
    id: onReleaseDown2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: "on"
    id: on3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: "off"
    id: off3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: stop_with_on_off
    id: onRelease3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: stop
    id: onReleaseDown3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: "on"
    id: on4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: "off"
    id: off4
  - platform: event
    event_type:
