blueprint:
  name: NAMRON 4 Channel ZigBee Switch v2.1
  description: Controls lights based on ZHA events with default actions for each endpoint.
  domain: automation
  input:
    device_id:
      name: Device ID
      description: The device ID of the ZHA switch.
      selector:
        text: {}
    light_entity_1:
      name: Light Entity 1
      description: The light entity controlled by endpoint 1.
      selector:
        entity:
          domain: light
    light_entity_2:
      name: Light Entity 2
      description: The light entity controlled by endpoint 2.
      selector:
        entity:
          domain: light
    light_entity_3:
      name: Light Entity 3
      description: The light entity controlled by endpoint 3.
      selector:
        entity:
          domain: light
    light_entity_4:
      name: Light Entity 4
      description: The light entity controlled by endpoint 4.
      selector:
        entity:
          domain: light

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: "on"
    id: on1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: "off"
    id: off1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: stop_with_on_off
    id: onRelease1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 1
      command: stop
    id: onReleaseDown1
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: "on"
    id: on2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: "off"
    id: off2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: stop_with_on_off
    id: onRelease2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 2
      command: stop
    id: onReleaseDown2
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: "on"
    id: on3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: "off"
    id: off3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: stop_with_on_off
    id: onRelease3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 3
      command: stop
    id: onReleaseDown3
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: "on"
    id: on4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: "off"
    id: off4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: move_with_on_off
      args:
        - 0
        - 50
    id: onHold4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: stop_with_on_off
    id: onRelease4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: move
      args:
        - 1
        - 50
        - 0
        - 0
    id: offHold4
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input device_id
      endpoint_id: 4
      command: stop
    id: onReleaseDown4

action:
  - choose:
      - conditions:
          - condition: trigger
            id: on1
        sequence:
          - data:
              entity_id: !input light_entity_1
            action: light.turn_on
      - conditions:
          - condition: trigger
            id: off1
        sequence:
          - data:
              entity_id: !input light_entity_1
            action: light.turn_off
      - conditions:
          - condition: trigger
            id: onHold1
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: onHold1
              sequence:
                - data:
                    brightness_step: 10
                  target:
                    entity_id: !input light_entity_1
                  action: light.turn_on
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 20
      - conditions:
          - condition: trigger
            id: offHold1
        sequence:
          - repeat:
              while:
                - condition: and
                  conditions:
                    - condition: trigger
                      id: offHold1
                - condition: numeric_state
                  entity_id: !input light_entity_1
                  value_template: >-
                    {% if states[!input light_entity_1].state == "on"  %}{{
                    states[!input light_entity_1].attributes.brightness }}{% else %}0{% endif %}
                  above: 2
                  attribute: brightness
              sequence:
                - data:
                    brightness_step_pct: -10
                  target:
                    entity_id: !input light_entity_1
                  action: light.turn_on
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 20
      - conditions:
          - condition: trigger
            id: onReleaseDown1
        sequence:
          - data:
              entity_id: !input light_entity_1
              brightness_pct: 1
            action: light.turn_on
          
      # Repeat similar action sequences for other endpoints
      # Replace endpoint ID and light entity as needed

      - conditions:
          - condition: trigger
            id: on2
        sequence:
          - data:
              entity_id: !input light_entity_2
            action: light.turn_on
      - conditions:
          - condition: trigger
            id: off2
        sequence:
          - data:
              entity_id: !input light_entity_2
            action: light.turn_off
      - conditions:
          - condition: trigger
            id: onHold2
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: onHold2
              sequence:
                - data:
                    brightness_step: 10
                  target:
                    entity_id: !input light_entity_2
                  action: light.turn_on
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 20
      - conditions:
          - condition: trigger
            id: offHold2
        sequence:
          - repeat:
              while:
                - condition: and
                  conditions:
                    - condition: trigger
                      id: offHold2
                - condition: numeric_state
                  entity_id: !input light_entity_2
                  value_template: >-
                    {% if states[!input light_entity_2].state == "on"  %}{{
                    states[!input light_entity_2].attributes.brightness }}{% else %}0{% endif %}
                  above: 2
                  attribute: brightness
              sequence:
                - data:
                    brightness_step_pct: -10
                  target:
                    entity_id: !input light_entity_2
                  action: light.turn_on
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 20
      - conditions:
          - condition: trigger
            id: onReleaseDown2
        sequence:
          - data:
              entity_id: !input light_entity_2
              brightness_pct: 1
            action: light.turn_on

      - conditions:
          - condition: trigger
            id: on3
        sequence:
          - data:
              entity_id: !input light_entity_3
            action: light.turn_on
      - conditions:
          - condition: trigger
            id: off3
        sequence:
          - data:
              entity_id: !input light_entity_3
            action: light.turn_off
      - conditions:
          - condition: trigger
            id: onHold3
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: onHold3
              sequence:
                - data:
                    brightness_step: 10
                  target:
                    entity_id: !input light_entity_3
                  action: light.turn_on
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 20
      - conditions:
          - condition: trigger
            id: offHold3
        sequence:
          - repeat:
              while:
                - condition: and
                  conditions:
                    - condition: trigger
                      id: offHold3
                - condition: numeric_state
                  entity_id: !input light_entity_3
                  value_template: >-
                    {% if states[!input light_entity_3].state == "on"  %}{{
                    states[!input light_entity_3].attributes.brightness }}{% else %}0{% endif %}
                  above: 2
                  attribute: brightness
              sequence:
                - data:
                    brightness_step_pct: -10
                  target:
                    entity_id: !input light_entity_3
                  action: light.turn_on
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 20
      - conditions:
          - condition: trigger
            id: onReleaseDown3
        sequence:
          - data:
              entity_id: !input light_entity_3
              brightness_pct: 1
            action: light.turn_on

      - conditions:
          - condition: trigger
            id: on4
        sequence:
          - data:
              entity_id: !input light_entity_4
            action: light.turn_on
      - conditions:
          - condition: trigger
            id: off4
        sequence:
          - data:
              entity_id: !input light_entity_4
            action: light.turn_off
      - conditions:
          - condition: trigger
            id: onHold4
        sequence:
          - repeat:
              while:
                - condition: trigger
                  id: onHold4
              sequence:
                - data:
                    brightness_step: 10
                  target:
                    entity_id: !input light_entity_4
                  action: light.turn_on
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 20
      - conditions:
          - condition: trigger
            id: offHold4
        sequence:
          - repeat:
              while:
                - condition: and
                  conditions:
                    - condition: trigger
                      id: offHold4
                - condition: numeric_state
                  entity_id: !input light_entity_4
                  value_template: >-
                    {% if states[!input light_entity_4].state == "on"  %}{{
                    states[!input light_entity_4].attributes.brightness }}{% else %}0{% endif %}
                  above: 2
                  attribute: brightness
              sequence:
                - data:
                    brightness_step_pct: -10
                  target:
                    entity_id: !input light_entity_4
                  action: light.turn_on
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: 20
      - conditions:
          - condition: trigger
            id: onReleaseDown4
        sequence:
          - data:
              entity_id: !input light_entity_4
              brightness_pct: 1
            action: light.turn_on
